# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "test", name: "Paul")
User.create(username: "testing", name: "Mike")
User.create(username: "tested", name: "Dan")

Project.create(name: "Mod 3 project", description: "Asynchronous SPA using vJS and Rails", notes: "Mustache copper mug hell of velit coloring book asymmetrical. Authentic 3 wolf moon irure poke organic veniam celiac chillwave enim eu tofu gluten-free vexillologist occaecat. Mumblecore commodo roof party, meditation dreamcatcher veniam ramps exercitation offal narwhal 90's sriracha incididunt. Ad deserunt thundercats man braid live-edge glossier mollit umami dolor vape snackwave. Locavore semiotics wolf man bun aliquip. Consequat hella marfa stumptown try-hard et cred.
  Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 2)
Project.create(name: "Denver Coffee", description: "Backburner no more", notes: "Measure twice, cut once. Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 3)
Project.create(name: "Other Thing", description: "you know, that other thing", notes: "revise and implement. Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 3)
Project.create(name: "Next Thing", description: "you know, the NEXT thing", notes: "revise and implement. Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 3)
Project.create(name: "My Thing", description: "oh yea, that's my thing", notes: "revise and implement. Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 3)
Project.create(name: "Those Things", description: "you know, those other things", notes: "revise and implement. Small batch irony green juice, butcher hot chicken vape stumptown kickstarter man bun lumbersexual pork belly twee. Commodo culpa squid four dollar toast. Intelligentsia franzen tumeric brunch. La croix pork belly sed twee synth man braid, slow-carb veniam elit.
  Pop-up typewriter health goth, portland lorem brunch kogi. Nulla pork belly green juice, cray bespoke flannel eu enamel pin heirloom. PBR&B VHS yr elit knausgaard. Pariatur enamel pin microdosing meditation magna, anim tousled twee crucifix nisi vice tempor copper mug brunch. Sustainable tofu four loko microdosing, mlkshk pour-over cronut tilde nisi vaporware tattooed biodiesel air plant. Pork belly vaporware keytar master cleanse quinoa DIY eu biodiesel. Poke glossier taxidermy VHS snackwave veniam locavore austin iPhone thundercats asymmetrical.
  Oh. You need a little dummy text for your mockup? How quaint.Make a plan and stick to it, making accommodations where needed.", user_id: 3)